global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - '172.31.43.242:9100'
        - '172.31.39.245:9100'

rule_files:
  - 'prometheus_rule.yml'
  - 'alerting_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

